FROM node:22-alpine

WORKDIR /app

COPY package*.json tsconfig.json postcss.config.mjs tailwind.config.ts next.config.ts ./
RUN npm ci

COPY . .

EXPOSE 3000

ENV PORT=3000
ENV HOSTNAME="0.0.0.0"

CMD ["npm", "run", "dev"]
